InternationalB2BVentures/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from apps.core.views import Index, SearchItem
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('search/', SearchItem, name="search"),
    path('tinymce/', include('tinymce.urls')),
    path("accounts/", include("apps.accounts.urls"), ),
    path("notification/", include("apps.notifications.urls"), ),
    path("vendor/", include("apps.vendor.urls"), ),
    path("core/", include("apps.core.urls"), ),

    # APIS
    path('api/vendor/', include('apps.vendor.api.urls')),
    path('api/notifications/', include('apps.notifications.api.urls')),
    
    path('api/', include('apps.core.api.urls')),
    
    # API Documentation
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    
    
]

urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/notifications/urls.py
from django.urls import path
from notifications.views import SubscribeForNewsLetter, SubscriberList, SubscriberCreate, SubscriberDetail, ImageCreate, ImageList, ImageDetail, NewsletterList, NewsletterCreate, NewsletterDetail, NewsletterSentList, NewsletterSentCreate, NewsletterSentDetail, NewsTagList, NewsTagCreate, NewsTagDetail, TagCategoryList, TagCategoryCreate, TagCategoryDetail


app_name = "notification"
urlpatterns = [
    path('subscribe_newsletter/',SubscribeForNewsLetter.as_view(), name='subscribe_newsletter'),

    path('subscriberlist/', SubscriberList.as_view()),
    path('subscribercreate/', SubscriberCreate.as_view()), 
    path('subscriberdetail/<int:pk>', SubscriberDetail.as_view()),
    path('newsletterlist/', NewsletterList.as_view()),
    path('newslettercreate/', NewsletterCreate.as_view()), 
    path('newsletterdetail/<int:pk>', NewsletterDetail.as_view()),
    path('imagelist/', ImageList.as_view()),
    path('imagecreate/', ImageCreate.as_view()), 
    path('imagedetail/<int:pk>', ImageDetail.as_view()),
    path('newslettersentlist/', NewsletterSentList.as_view()),
    path('newslettersentcreate/', NewsletterSentCreate.as_view()), 
    path('newslettersentdetail/<int:pk>', NewsletterSentDetail.as_view()),
    path('newstaglist/', NewsTagList.as_view()),
    path('newstagcreate/', NewsTagCreate.as_view()), 
    path('newstagdetail/<int:pk>', NewsTagDetail.as_view()),
    path('tagcategorylist/', TagCategoryList.as_view()),
    path('tagcategorycreate/', TagCategoryCreate.as_view()), 
    path('tagcategorydetail/<int:pk>', TagCategoryDetail.as_view()),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="msapplication-TileColor" content="#0E0E0E">
  <meta name="template-color" content="#0E0E0E">
  <meta name="description" content="Index page">
  <meta name="keywords" content="index, page">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'imgs/template/favicon.svg' %}">
  <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
  <style>
    .error_list {
      color: #ff7588;
    }

    .rc-anchor-center-item {
      display: table-cell;
      vertical-align: top;
      margin-top: 10px;
      padding-top: 10px;
    }

    .rc-anchor-normal {
      height: 74px;
      width: 300px;
      max-height: 47px;
    }

    option {
      color: white;
    }
  </style>

  <link href="{% static 'css/style.css' %}?v=3.0.0" rel="stylesheet">
  {% block style %} {% endblock %}
  <title>{% block title %}IB2BV{% endblock %}</title>
</head>

<body>
  {% block preloader %}
  <div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
      <div class="preloader-inner position-relative">
        <div class="text-center">
          <img class="mb-10" src="{% static 'imgs/logo.jpg' %}" alt="IB2BV">
          <div class="preloader-dots"></div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}


  <!-- block header %} -->
  {% include 'header.html' %}
  <!-- endblock %} -->

  <main class="main bg-secondary">
    
    <!-- breadcrumb links  -->
    <div class="section-box">
      <div class="breadcrumbs-div mt-15 mb-15">
        <div class="container">
          <ul class="breadcrumb">
            <li>
              <a class="color-gray-1000 active text-primary" href="/" > 
                <small style=" font-size: 12px; ">You Are Here : </small> 
                <strong>Home</strong> 
              </a>
            </li>
            {% block links %} {% endblock %}
          </ul>
        </div>
      </div>
    </div>
    <!-- end breadcrumb links  -->

    <!-- message area -->
    <div class="message-container">
      {% for msg in messages %}
      <div role="alert" class="alert alert-{{msg.tags}} alert-dismissible ">
        <button type="button" class="btn-close no-border" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong>{{msg.tags|title}}!</strong> {{msg|safe}}
      </div>
      {% endfor %}

    </div>
    <!-- end of message area -->

    {% block main %}
    {% endblock %}

  </main>


  {% block footer %}
  {% include 'footer.html' %}
  {% endblock %}


  <script src="{% static 'js/vendors/modernizr-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/vendors/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'js/vendors/jquery-migrate-3.3.0.min.js' %}"></script>
  <script src="{% static 'js/vendors/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/vendors/waypoints.js' %}"></script>
  <script src="{% static 'js/vendors/wow.js' %}"></script>
  <script src="{% static 'js/vendors/magnific-popup.js' %}"></script>
  <script src="{% static 'js/vendors/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/vendors/select2.min.js' %}"></script>
  <script src="{% static 'js/vendors/isotope.js' %}"></script>
  <script src="{% static 'js/vendors/scrollup.js' %}"></script>
  <script src="{% static 'js/vendors/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'js/vendors/noUISlider.js' %}"></script>
  <script src="{% static 'js/vendors/slider.js' %}"></script>
  <!-- Count down-->
  <script src="{% static 'js/vendors/counterup.js' %}"></script>
  <script src="{% static 'js/vendors/jquery.countdown.min.js' %}"></script>
  <!-- Count down-->
  <script src="{% static 'js/vendors/jquery.elevatezoom.js' %}"></script>
  <script src="{% static 'js/vendors/slick.js' %}"></script>
  <script src="{% static 'js/main.js' %}?v=3.0.0"></script>
  <script src="{% static 'js/shop.js' %}?v=1.2.1"></script>
  <script src="{% static 'js/custom_main.js' %}"></script>

  {% block script %}
  {% endblock %}
</body>

</html>

templates/footer.html
<!-- footer.html -->
{% load static %}
<footer class="footer ">

    <div class="footer-2" style="border-top: 1px solid #CAD6EC; background-color: #131a22; color: white;">
        <div class="container-fluid">
            <div class="footer-bottom">
                <div class="d-flex" style="flex-direction: column; justify-content: center; align-items: center;">
                    <!-- top news -->
                    <section class="section-box box-newsletter p-0 w-50 bg-none mb-40">
                        <div class="container">
                            <div class="mb-15 mt-5">
                                <h5 class="text-center text-white mb-30">NEWSLETTER</h5>
                                <p class="text-center text-white text-gray">Subscribe to our newsletter for updates and special updates!</p>    
                            </div>

                            <div class="box-form-newsletter ">
                                <form id="form" class="form-newsletter"  method="post" action="{% url 'notification:subscribe_newsletter' %}"> 
                                    {% csrf_token %}
                                    <input id="email" type="email" class="input-newsletter font-xs" value="" name="email" placeholder="YOUR EMAIL ... ">
                                    <button  type="submit" class="btn btn-brand-2" >Sign Up</button>
                                </form>
                            </div>
                        </div>
                    </section>
                    <section class="w-50 mt-20">
                        <div class="row justify-content-center text-center">
                            <div class="col-5"><a class="font-md text-white" href="">Whats New</a></div>
                            <div class="col-5"><a class="font-md text-white" href="">About Us</a></div>
                            <div class="col-5"><a class="font-md text-white" href="">Terms and Conditions</a></div>
                            <div class="col-5"><a class="font-md text-white" href="">Contact Us</a></div>
                        </div>
                        <div class="mt-20 text-center" style="width: 100%;">
                            <span class="text-white font-xs"> Copyright &copy; IB2BV, Inc 
                                <script>document.write(new Date().getFullYear())</script> 
                            </span>
                            
                        </div>

                    </section>
                </div>


            </div>
        </div>
    </div>
</footer>

{% block script %} 
<script>
    // function subscribe(){

    //     $.ajax({
    //               type:'POST',
    //               url: "{% url 'notification:subscribe_newsletter' %}",
    //               data: {'email':$("#email").val(), },
    //               headers: {
    //                 'X-Requested-With': 'XMLHttpRequest',
    //                 'HTTP_X_CSRFTOKEN': "{% csrf_token %}"
    //             },  // Include CSRF token in the headers
    //               success: function (response,) {
    //                   alert(response.msg);
    //                   },
    //               error: function (response) {
    //                   alert("Error while");
    //               }
    //           })
    // }

    // function neww(){
        
        

    // }
    // function submit_subscriber(form){
    //     // this.preventDefault();
    //     email = document.getElementById('email').innerHTML
        
        
    // }
</script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<!-- Top  -->

<section class="section-box ">
  <div class="container">
    <div class="head-main border-none m-0">
      <div class="row">
        <div class="col-xl-5 col-lg-6 ">

        </div>
        <div class="col-xl-7 col-lg-6 ">
          <h3 class="mb-20 mt-20 " style="left:-90px; position: relative; color: #4e4e4e">Meet Our Top 10 Vendors!</h3>
        </div>
      </div>
    </div>
    <div class="list-products-5">

      {% for vendor in vendors %}
      <div class="card-grid-style-3 px-2">
        <div class="card-grid-inner p-0 border-none bg-none">
          <div class="image-box">
            <a href="/" style="display: block; border-radius: 10px 10px 0 0;">
              <img src="{{vendor.logo.url}}" alt="IB2BV"></a>
          </div>
          <div class="text-center px-3">
            <a class="color-brand-3 font-md-bold" href="">{{vendor.name}}.</a>
            <br>
            <a class="font-xs color-gray-500 d-none" href=""></a>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</section>

<!-- End of Top -->


<!-- Why choose us -->
<section class="section-box mt-70 mb-50">
  <div class="container">
    <div class="head-main text-center mb-10 border-none">
      <h3 class="mb-5 text-dark">WHY US</h3>
      <p class="font-base color-gray-500">Here is why our clients choose us!</p>
    </div>
  </div>
  <div class="container mt-10">
    <div class="box-swiper">
      <div class="swiper-container swiper-group-4">
        <div class="swiper-wrapper py-5">
          {% for item in whyus %}
          <div class="swiper-slide">
            <div class="item-list">
              <div class="icon-left"><img src="{{item.icon.url}}" alt="IB2BV"></div>
              <div class="info-right">
                <h5 class="font-lg-bold color-gray-100 text-dark">{{item.title}}</h5>
                <p class="font-sm color-gray-500">{{item.content}}</p>
              </div>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- End of why choose us -->

<!-- List of Vendors -->
<div class="section-box mt-70">
  <div class="container" style="max-width: 90%;">
    <div class="box-filters mt-0 pb-5 mb-10">
      <div class="row" style="border-bottom: 1px solid #D5DFE4;">


        <div class="col-xl-4 col-md-5 mb-10 text-md-start text-center ">
          <a class="btn btn-filter font-sm color-brand-3 font-medium " href="#ModalFiltersForm"
            data-bs-toggle="modal">All Filters</a>

          <select class=" select2-container ml-20 py-2 px-2 border-none bg-primary text-white rounded"
           onchange="filterVendors(this.value)">
            <option class="">All categories</option>
            {% for cat in vendor_cats %}
            <option value="{{cat.name}}">{{cat.name}}</option>
            {% endfor %}
          </select>

        </div>

        <div class="col-xl-8 col-md-7 mb-10 text-md-end text-center">

          <span class="d-inline-block font-md border-1-right span ">Showing 1&ndash;16 of 17 </span>

          <div class="d-inline-block"><span class="font-md color-gray-500 ">Show</span>
            <div class="dropdown dropdown-sort border-1-right text-primary">
              <button class="btn dropdown-toggle font-md " id="dropdownSort2" type="button" data-bs-toggle="dropdown"
                aria-expanded="false" data-bs-display="static">
                <span class="text-primary">30 items</span>
              </button>
              <ul class="dropdown-menu dropdown-menu-light " aria-labelledby="dropdownSort2">
                <li><a class="dropdown-item active" href="#">30 items</a></li>
                <li><a class="dropdown-item" href="#">50 items</a></li>
                <li><a class="dropdown-item" href="#">100 items</a></li>
              </ul>
            </div>
          </div>

          <div class="d-inline-block"><span class="font-sm color-gray-500 font-medium ">Sort by:</span>
            <div class="dropdown dropdown-sort border-1-right">
              <button class="btn dropdown-toggle font-sm color-gray-900 font-medium " id="dropdownSort" type="button"
                data-bs-toggle="dropdown" aria-expanded="false">Latest products</button>
              <ul class="dropdown-menu dropdown-menu-light " aria-labelledby="dropdownSort" style="margin: 0px;">
                <li><a class="dropdown-item active" href="#">Latest products</a></li>
                <li><a class="dropdown-item" href="#">Oldest products</a></li>
                <li><a class="dropdown-item" href="#">Comments products</a></li>
              </ul>
            </div>
          </div>

        </div>

      </div>
    </div>
  </div>

</div>

<section class="section-box mt-10 mb-20">
  <div class="container">

    <div class="mt-10 mb-10">
      <ul class="list-9-col">
        {% for vendor in vendors %}
        <li class="vendor-item {{vendor.category}}">
          <div class="box-category hover-up ">
            <a href="">
              <div class="image"><img src="{{vendor.logo.url}}" alt="Ibbv"></div>
            </a>
            <div class="text-info">
              <a class="font-sm color-gray-900 font-bold" href="">{{vendor.name}}</a>
            </div>
          </div>
        </li>
        {% endfor %}

      </ul>
    </div>

    <nav class="right">
      <ul class="pagination">
        <li class="page-item"><a class="page-link page-prev" ></a></li>
        <li class="page-item"><a class="page-link active" >1</a></li>
        <li class="page-item"><a class="page-link page-next" ></a></li>      
      </ul>
    </nav>
  </div>
</section>
<!-- End of List of Vendors -->

<!-- News Slider -->

<section class="section-box mt-10 mb-50">
  <div class="container">
    <div class="head-main ">
      <h3 class="mb-5 text-dark">Latest News</h3>
      <p class="font-base color-gray-500">Get updates about latest activities!</p>
    </div>
  </div>

  <div class="container box-slider-item">
    <div class="content-slider">
      <div class="box-swiper">
        <div class="swiper-button-next swiper-button-next-style-2 swiper-button-next-bestseller"></div>
        <div class="swiper-button-prev swiper-button-prev-style-2 swiper-button-prev-bestseller"></div>

        <div class="swiper-container swiper-best-seller">
          <div class="swiper-wrapper pt-5">

            {% for item in news %}
            <div class="swiper-slide">
              <div class="col-12 display-list display-list-2">
                <div class="card-grid-style-1">
                  <div class="image-box">
                    <a href="/">
                      {% for img in item.images.all %}
                      <img src="{{img.file.url}}" alt="Ibbv">
                      {% endfor %}
                    </a>
                  </div>
                  <div class="blog-info">
                    {% for tag in item.tags.all %}
                    <a class="tag-dot font-xs" href="/">
                    {{tag}}
                    </a>
                    {% endfor %}
                    <a class="color-gray-1100" href="/">
                      <h4 class="mb-15">{{item.title}} </h4>
                    </a>
                    <p class="font-md color-gray-500 min-height-135">{{item.content}}</p>
                    <div class="row mt-20">
                      <div class="col-8"><span class="color-gray-500 font-sm mr-30">{{item.publication_date}}</span>
                      </div>
                      <div class="col-4 text-end"><a class="btn btn-arrow-2 btn-arrow-2-reverse">Read more</a></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}

          </div>
        </div>

      </div>
    </div>
  </div>
</section>
<!-- End of News Slider -->


<div class="modal fade" id="ModalFiltersForm" tabindex="-1" aria-hidden="true" style="display: none;">
  <div class="modal-dialog modal-xl">
    <div class="modal-content apply-job-form">
      <div class="modal-header">
        <h5 class="modal-title color-gray-1000 filters-icon">Advance Filters</h5>
        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body p-30">
        <div class="row">
          <div class="col-w-1">
            <h6 class="color-gray-900 mb-0">Category</h6>
            <ul class="list-checkbox">
              {% for cat in vendor_cats %}
              <li>
                <label class="cb-container">
                  <input type="checkbox" {% if forloop.counter == 1 %} checked="checked" {% endif %}><span
                    class="text-small">{{cat}}</span><span class="checkmark"></span>
                </label>
              </li>
              {% endfor %}

            </ul>
          </div>

          <!-- Filter by tags -->
          <div class="col-w-2">
            <h6 class="color-gray-900 mb-20 mt-40">Tags</h6>
            <div><a class="btn btn-border mr-5" href="#">Games</a><a class="btn btn-border mr-5"
                href="#">Electronics</a><a class="btn btn-border mr-5" href="#">Video</a><a class="btn btn-border mr-5"
                href="#">Cellphone</a><a class="btn btn-border mr-5" href="#">Indoor</a><a class="btn btn-border mr-5"
                href="#">VGA Card</a><a class="btn btn-border mr-5" href="#">USB</a><a class="btn btn-border mr-5"
                href="#">Lightning</a><a class="btn btn-border mr-5" href="#">Camera</a>
            </div>
          </div>

          <div class="col-w-2">
            <h6 class="color-gray-900 mb-0 mt-40">Rating</h6>
            <ul class="list-checkbox">
              <li class="mb-5"><a href="#"><img src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><span
                    class="ml-10 font-xs color-gray-500 d-none d-inline-block align-top">(5 stars)</span></a></li>
              <li class="mb-5"><a href="#"><img src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><span
                    class="ml-10 font-xs color-gray-500 d-none d-inline-block align-top">(4 stars)</span></a></li>
              <li class="mb-5"><a href="#"><img src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><span
                    class="ml-10 font-xs color-gray-500 d-none d-inline-block align-top">(3 stars)</span></a></li>
              <li class="mb-5"><a href="#"><img src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><span
                    class="ml-10 font-xs color-gray-500 d-none d-inline-block align-top">(2 stars)</span></a></li>
              <li class="mb-5"><a href="#"><img src="{% static 'imgs/template/icons/star.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><img
                    src="{% static 'imgs/template/icons/star-gray.svg' %}" alt="IB2BV"><span
                    class="ml-10 font-xs color-gray-500 d-none d-inline-block align-top">(1 star)</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="modal-footer justify-content-start pl-30"><a class="btn btn-buy w-auto" href="#">Apply Filter</a><a
          class="btn font-sm-bold color-gray-500" href="#">Reset Filter</a></div>
    </div>
  </div>
</div>

{% endblock %}

{% block script %}
<script>
  function filterVendors(filterTag=""){
    // console.log("Select is ", category);
    $('.vendor-item').each((i, item)=>{
      if (filterTag == 'All categories' || item.className.includes(filterTag)){
        $(item).css('display', 'block');
      }
      else{
        $(item).css('display', 'none');
      }
      
    })  
    
   
  }
  
</script>
{% endblock %}